Repository 2025-HERETHON/2025-herethon-9, pull requests merged in 2025-07, with the labels that each got.

#6 ✨Feat: 전문가 매칭(예약하기) 기능 구현
  MYworkHER/MYworkHER/settings.py
  MYworkHER/MYworkHER/urls.py
  MYworkHER/accounts/forms.py
  MYworkHER/accounts/models.py
  MYworkHER/accounts/templates/accounts/login.html
  MYworkHER/accounts/templates/accounts/mypage.html
  MYworkHER/accounts/templates/accounts/signup.html
  MYworkHER/accounts/urls.py
  MYworkHER/matching/forms.py
  MYworkHER/matching/models.py
  MYworkHER/matching/templates/matching/matching.html
  MYworkHER/matching/templates/matching/success.html
  MYworkHER/matching/urls.py
  MYworkHER/matching/views.py
  requirement.txt
Labels: ✨ Feat

#10 🐛Fix: 전문가 예약 기능 구현 및 예약 페이지 수정
  MYworkHER/matching/templates/matching/main.html
  MYworkHER/matching/templates/matching/matching.html
  MYworkHER/matching/templates/matching/success.html
  MYworkHER/matching/urls.py
  MYworkHER/matching/views.py
Labels: 🐛 BugFix, ✨ Feat

#12 feat: 로그인 및 회원가입 UI 구현 (#11)
  .vscode/settings.json
  frontend/assets/img/check.png
  frontend/assets/img/customer.png
  frontend/assets/img/expert.png
  frontend/assets/img/login_logo.svg
  frontend/assets/img/mdi_camera.svg
  frontend/css/complete.css
  frontend/css/login.css
  frontend/css/profile.css
  frontend/css/purpose.css
  frontend/css/signup.css
  frontend/css/verify.css
  frontend/js/complete.js
  frontend/js/login.js
  frontend/js/profile.js
  frontend/js/purpose.js
  frontend/js/signup.js
  frontend/js/verify.js
  frontend/pages/complete.html
  frontend/pages/login.html
  frontend/pages/profile.html
  frontend/pages/purpose.html
  frontend/pages/signup.html
  frontend/pages/verify.html
Labels: ✨ Feat

#29 🐛 Fix: 예약 날짜 저장 시 NULL 값 발생 문제 해결
  MYworkHER/matching/templates/matching/matching.html
  MYworkHER/matching/views.py
Labels: 🐛 BugFix

#35 feat: 전문가 페이지 (회원 목록) UI 구현 (#31)
  frontend/assets/img/search-icon.svg
  frontend/components/admin-navbar.css
  frontend/components/admin-navbar.html
  frontend/components/admin-navbar.js
  frontend/css/common.css
  frontend/css/user_list.css
  frontend/js/chat.js
  frontend/js/common.js
  frontend/js/user_list.js
  frontend/pages/chat.html
  frontend/pages/user_list.html
Labels: ✨ Feat

#60 전문가 예약하기 페이지 연동
  MYworkHER/matching/templates/matching/main.html
  MYworkHER/matching/templates/matching/reserve.html
  MYworkHER/matching/templates/matching/reserve_confirm.html
  MYworkHER/matching/urls.py
  MYworkHER/matching/views.py
  MYworkHER/pages/reserve.html
  MYworkHER/pages/reserve_confirm.html
  MYworkHER/static/css/reserve.css
  MYworkHER/static/css/reserve_confirm.css
  MYworkHER/static/img/appliance.svg
  MYworkHER/static/img/business.svg
  MYworkHER/static/img/health.png
  MYworkHER/static/img/lifestyle.svg
  MYworkHER/static/js/reserve.js
  MYworkHER/static/js/reserve_confirm.js
Labels: ✨ Feat
